name: "pre-release"

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches: [ "dev" ]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: "Build & test"
        run: |
          cargo build --release --verbose
          cp target/release/release kenshi

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            kenshi
